<?
		$msg = "<html>";
		$msg .="<head>";
		$msg .="<title></title>";
		$msg .="<meta http-equiv='content-type' content='text/html; charset=iso-8859-1'>";
		$msg.="<style type='text/css'>";
		$msg.="body{margin:0;font-family:verdana,arial,helvetica;font-size:10px;color:#666666}";
		$msg.="input,select,textarea{font-family:verdana,arial,helvetica;font-size:10px;}";
		$msg.=".boxnormal {font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 10px; border-style: solid;border-width: 1;color:#666666; background-color: White;}";
		$msg.=".boxover {font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 10px; border-style: solid;border-width: 1;color:#666666; background-color: #F0F0F0;}";
		$msg.=".font-preto{color:#000000}";
		$msg.=".font-cinza-1{color:#999999}";
		$msg.=".font-cinza-2{color:#CCCCCC}";
		$msg.=".font-vinho{color:#CC3300}";
		$msg.=".font-laranja{color:#FFA629}";
		$msg.=".font-azul{color: #00008B;}";
		$msg.=".font-branco{color:#FFFFFF}";
		$msg.=".font-09{font-size:9px}";
		$msg.=".font-10{font-size:10px}";
		$msg.=".font-11{font-size:11px}";
		$msg.=".font-12{font-size:12px}";
		$msg.=".font-13{font-size:13px}";
		$msg.=".font-14{font-size:14px}";
		$msg.=".form-especial {font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 10px; border-style: solid;border-width: 1;color:#666666}";
		$msg.=".form-busca {font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 10px; color: #666666; border: 1px inset #999999;}";
		$msg.=".line-height-0{line-height:9px}";
		$msg.=".line-height-1{line-height:10px}";
		$msg.=".line-height-2{line-height:13px}";
		$msg.=".line-height-3{line-height:16px}";
		$msg.=".line-height-4{line-height:18px}";
		$msg.=".line-height-5{line-height:24px}";
		$msg.=".bg-preto{background:#000000}";
		$msg.=".bg-cinza{background:#CCCCCC}";
		$msg.=".bg-cinza-gelo{background: #F5F5F5}";
		$msg.=".bg-branco{background:#FFFFFF}";
		$msg.=".menu a:link{font-family:tahoma, arial, helvetica;font-size:11px;color:#666666;text-decoration:none}";
		$msg.=".menu a:active{font-family:tahoma, arial, helvetica;font-size:11px;color:#666666;text-decoration:none}";
		$msg.=".menu a:visited{font-family:tahoma, arial, helvetica;font-size:11px;color:#666666;text-decoration:none}";
		$msg.=".menu a:hover{font-family:tahoma, arial, helvetica;font-size:11px;color: #FFFFFF;text-decoration: none}";
		$msg.="a:link{color:#666666;text-decoration:none}";
		$msg.="a:active{color:#666666;text-decoration:none}";
		$msg.="a:visited{color:#666666;text-decoration:none}";
		$msg.="a:hover{color: Red;text-decoration: none}";
		$msg.="#dek {POSITION:absolute;VISIBILITY:hidden;Z-INDEX:200;}";
		$msg.="TD {";
		$msg.="	FONT-SIZE: 12px; FONT-FAMILY: MS Sans Serif, sans-serif, Arial, Helvetica";
		$msg.="}";
		$msg.="TH {";
		$msg.="	FONT-SIZE: 12px; FONT-FAMILY: MS Sans Serif, sans-serif, Arial, Helvetica";
		$msg.="}";
		$msg.="P {";
		$msg.="	FONT-SIZE: 12px; FONT-FAMILY: MS Sans Serif, sans-serif, Arial, Helvetica";
		$msg.="}";
		$msg.="SPAN {";
		$msg.="	FONT-SIZE: 12px; FONT-FAMILY: MS Sans Serif, sans-serif, Arial, Helvetica";
		$msg.="}";
		$msg.="DIV {";
		$msg.="	FONT-SIZE: 12px; FONT-FAMILY: MS Sans Serif, sans-serif, Arial, Helvetica";
		$msg.="}";
		$msg.="</style>";
		$msg .="</head><body bgcolor='#ffffff' leftmargin='0' topmargin='0' marginwidth='0' marginheight='0'>";
		$msg .="<center>";
		$msg.="<table border='0' width='600' cellspacing='1' cellpadding='0'>";
		$msg.="    <tr>";
		$msg.="      <td width='600'><font class=font-10><span class=font-vinho>Data :</span></font></td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td width='600'>".$_POST['data_d']."";
		$msg.="        /";
		$msg.="        ".$_POST['data_m']."";
		$msg.="        /";
		$msg.="        ".$_POST['data_a']."</td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td width='600'><font class=font-10><span class=font-vinho>Programar :</span></font></td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td width=600><table width='100%' border='0' cellspacing='0' cellpadding='0'>";
		$msg.="        <tr>";
		$msg.="          <td width='16%'>".$_POST['programar']."</td>";
		$msg.="          <td width='58%'><span class='font-vinho'>Para dia: </span>";
		$msg.="                ".$_POST['para_d'];
		$msg.="            /";
		$msg.="            ".$_POST['para_m'];
		$msg.="            /";
		$msg.="            ".$_POST['para_a'];
		$msg.="            dd/mm/aaaa </td>";
		$msg.="        </tr>";
		$msg.="      </table></td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td width='600'><font class=font-10><span class=font-vinho>Equipamento :</span></font></td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td width='600'>".$_POST['equipamento']."</td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td width='600'><font class=font-10><span class=font-vinho>Cliente :</span></font></td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td width='600'>".$_POST['cliente']."</td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td width='600'><font class=font-10><span class=font-vinho>Contrato :</span></font></td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td width='600'>".$_POST['contrato']."</td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td width='600'><font class=font-10><span class=font-vinho>Obra :</span></font></td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td width='600'>".$_POST['obra']."</td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td width='600'><font class=font-10><span class=font-vinho>Frete :</span></font></td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td width='600'><table width='100%' border='0' cellspacing='0' cellpadding='0'>";
		$msg.="        <tr>";
		$msg.="          <td width='16%'>".$_POST['frete']."</td>";
		$msg.="          <td width='58%'>&nbsp;</td>";
		$msg.="        </tr>";
		$msg.="      </table></td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td><font class=font-10><span class=font-vinho>Operador :</span></font></td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td><table width='100%' border='0' cellspacing='0' cellpadding='0'>";
		$msg.="        <tr>";
		$msg.="          <td width='20%'>".$_POST['operador']."</td>";
		$msg.="          <td width='58%'><span class='font-vinho'>Empresa: </span>";
		$msg.="                    ".$_POST['operador_select'];
		$msg.="          </td>";
		$msg.="        </tr>";
		$msg.="      </table></td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td><font class=font-vinho>Diesel : </font></td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td><table width='100%' border='0' cellspacing='0' cellpadding='0'>";
		$msg.="        <tr>";
		$msg.="          <td width='16%'>".$_POST['diesel']."</td>";
		$msg.="        </tr>";
		$msg.="      </table></td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td><font class=font-vinho>Estrutura F&iacute;sica de atendimento : </font></td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td width='600'><font class=font-10>";
		$msg.="        ".$_POST['estrutura'];
		$msg.="      </font></td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td><font class=font-vinho>Observa&ccedil;&otilde;es : </font></td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td width='600'>".$_POST['observacoes']."</td>";
		$msg.="    </tr>";
		$msg.="    <tr>";
		$msg.="      <td>&nbsp;</td>";
		$msg.="    </tr>";
		$msg.="  </form>";
		$msg.="</table>";
		$msg.="</center>";
		$msg.="</body>";
		$msg.="</html>";

		$headers = "MIME-Version: 1.0\n";
		$headers .= "Content-type: text/html; charset=iso-8859-1\n";
		$headers .= "From: $nome <$mail>\n";
		$headers .= "Return-Path: <lucas@cohrion.com.br>\n";
		
		/* Enviando a mensagem */
		mail("nadiclecio@escad.com.br ", "Programação de Entrada e Saída de Equipametos", $msg, $headers);
		mail("escad@escad.com.br ", "Programação de Entrada e Saída de Equipametos", $msg, $headers);

?>