beginSTM("yfatchr","static","0","0","none","false","false","310","20","0","250","","temas/imagens/spacer.gif");
	
	beginSTMB("auto","0","0","horizontally","","0","0","0","0","#cccccc","","tiled","#000000","1","none","0","Normal","70","0","0","0","0","0","0","0","#ffffff","false","#ffffff","#ffffff","#ffffff","none");

	
	//appendSTMI("false","<a href='index.php' onMouseOver=ShowHide('bthome','bthomeon'); onMouseOut=ShowHide('bthome','bthomeoff');><img border='0' name='bthome' src='temas/imagens/bthomeoff.gif'></a>","center","middle","","","101","53","5","normal","#ffffff","#cccccc","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","0","0","0","","","_self","Tahoma","9pt","#ffffff","normal","normal","none","Tahoma","9pt","#ffffff","normal","normal","none","0","solid","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","","temas/imagens/spacer.gif","temas/imagens/fade.gif","tiled","tilevd");
	
	
	
		appendSTMI("false","<a href='index.php' onMouseOver=ShowHide('bthome','bthomeon'); onMouseOut=ShowHide('bthome','bthomeoff');><img border='0' name='bthome' src='temas/imagens/bthomeoff.gif'></a>","center","middle","","","110","53","5","normal","#ffffff","#cccccc","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","0","0","0","","","_self","Tahoma","9pt","#ffffff","normal","normal","none","Tahoma","9pt","#ffffff","normal","normal","none","0","solid","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","","temas/imagens/spacer.gif","temas/imagens/fade.gif","tiled","tiled");

		beginSTMB("auto","0","0","vertically","","0","0","0","1","#4272B5","","tiled","#F58735","1","solid","0","Wipe down","25","8","0","0","0","0","0","0","#F58735","false","#F58735","#F58735","#F58735","none");
	
		appendSTMI("false","<span class='menu'><a href='MeusDados.php'>Meus Dados</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");
		//appendSTMI("false","<span class='menu'><a href='operador.php?modulo=buscar'>Visualizar Todos</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		endSTMB();


	appendSTMI("false","<a href='#' onMouseOver=ShowHide('btclientes','btclienteson'); onMouseOut=ShowHide('btclientes','btclientesoff');><img border='0' name='btclientes' src='temas/imagens/btclientesoff.gif'></a>","center","middle","","","110","53","5","normal","#ffffff","#cccccc","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","0","0","0","","","_self","Tahoma","9pt","#ffffff","normal","normal","none","Tahoma","9pt","#ffffff","normal","normal","none","0","solid","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","","temas/imagens/spacer.gif","temas/imagens/fade.gif","tiled","tiled");

		beginSTMB("auto","0","0","vertically","","0","0","0","1","#4272B5","","tiled","#F58735","1","solid","0","Wipe down","25","8","0","0","0","0","0","0","#AEC906","false","#F58735","#F58735","#F58735","none");

		appendSTMI("false","<span class='menu'><a href='obra.php?modulo=criar'>Adicionar Obra</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","<span class='menu'><a href='obra.php?modulo=buscar&por_tipo=a'>Visualizar em andamento</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","<span class='menu'><a href='obra.php?modulo=buscar&por_tipo=b'>Visualizar Finalizadas</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","<span class='menu'><a href='obra.php?modulo=buscar'>Visualizar Todos</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		endSTMB();

	appendSTMI("false","<a href='#' onMouseOver=ShowHide('btplanos','btplanoson'); onMouseOut=ShowHide('btplanos','btplanosoff');><img border='0' name='btplanos' src='temas/imagens/btplanosoff.gif'></a>","center","middle","","","110","53","5","normal","#ffffff","#cccccc","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","0","0","0","","","_self","Tahoma","9pt","#ffffff","normal","normal","none","Tahoma","9pt","#ffffff","normal","normal","none","0","solid","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","","temas/imagens/spacer.gif","temas/imagens/fade.gif","tiled","tiled");

    		beginSTMB("auto","0","0","vertically","","0","0","0","1","#4272B5","","tiled","#F58735","1","solid","0","Wipe down","25","8","0","0","0","0","0","0","#AEC906","false","#F58735","#F58735","#F58735","none");

		appendSTMI("false","<span class='menu'><a href='maquina.php?modulo=criar'>Adicionar Equipamento</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","<span class='menu'><a href='maquina.php?modulo=buscar&Status=n'>Visualizar Ativas</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");
		appendSTMI("false","<span class='menu'><a href='maquina.php?modulo=buscar&Status=s'>Visualizar Excluidas</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");
		appendSTMI("false","<span class='menu'><a href='maquina.php?modulo=localiza'>Buscar Maquina</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");
  		appendSTMI("false","","left","middle","","","11","11","0","normal","#F58735","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","9pt","#AEC906","normal","normal","none","Tahoma","9pt","#AEC906","normal","normal","none","0","none","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","","temas/imagens/spacer.gif","","tiled","tiled");  
		appendSTMI("false","<span class='menu'><a href='acessorio.php?modulo=criar'>Adicionar acessório</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");
	appendSTMI("false","<span class='menu'><a href='acessorio.php?modulo=buscar&Status=n'>Visualizar Ativos</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");
		appendSTMI("false","<span class='menu'><a href='acessorio.php?modulo=buscar&Status=s'>Visualizar Excluidos</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");
		appendSTMI("false","<span class='menu'><a href='acessorio.php?modulo=localiza'>Buscar acessório</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");
  		appendSTMI("false","","left","middle","","","11","11","0","normal","#F58735","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","9pt","#AEC906","normal","normal","none","Tahoma","9pt","#AEC906","normal","normal","none","0","none","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","","temas/imagens/spacer.gif","","tiled","tiled");  
		appendSTMI("false","<span class='menu'><a href='caminhao.php?modulo=criar'>Adicionar caminhão</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","<span class='menu'><a href='caminhao.php?modulo=buscar'>Visualizar Todas</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");
		
		appendSTMI("false","","left","middle","","","11","11","0","normal","#F58735","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","9pt","#AEC906","normal","normal","none","Tahoma","9pt","#AEC906","normal","normal","none","0","none","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","","temas/imagens/spacer.gif","","tiled","tiled");  
		appendSTMI("false","<span class='menu'><a href='proprietario.php?modulo=criar'>Adicionar Proprietário</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","<span class='menu'><a href='proprietario.php?modulo=buscar'>Visualizar Todas</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		endSTMB();

	appendSTMI("false","<a href='#' onMouseOver=ShowHide('btcobrancas','btcobrancason'); onMouseOut=ShowHide('btcobrancas','btcobrancasoff');><img border='0' name='btcobrancas' src='temas/imagens/btcobrancasoff.gif'></a>","center","middle","","","110","53","5","normal","#ffffff","#cccccc","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","0","0","0","","","_self","Tahoma","9pt","#ffffff","normal","normal","none","Tahoma","9pt","#ffffff","normal","normal","none","0","solid","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","","temas/imagens/spacer.gif","temas/imagens/fade.gif","tiled","tiled");

		beginSTMB("auto","0","0","vertically","","0","0","0","1","#4272B5","","tiled","#F58735","1","solid","0","Wipe down","25","8","0","0","0","0","0","0","#F58735","false","#F58735","#F58735","#F58735","none");
	
		appendSTMI("false","<span class='menu'><a href='operador.php?modulo=criar'>Adicionar Operador</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");
		appendSTMI("false","<span class='menu'><a href='operador.php?modulo=buscar&Status=A'>Visualizar Ativos</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");
		appendSTMI("false","<span class='menu'><a href='operador.php?modulo=buscar&Status=E'>Visualizar Excluidos</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");
appendSTMI("false","","left","middle","","","11","11","0","normal","#F58735","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","9pt","#AEC906","normal","normal","none","Tahoma","9pt","#AEC906","normal","normal","none","0","none","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","","temas/imagens/spacer.gif","","tiled","tiled");  

		appendSTMI("false","<span class='menu'><a href='mecanico.php?modulo=criar'>Adicionar Mecânico</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");
		appendSTMI("false","<span class='menu'><a href='mecanico.php?modulo=buscar&Status=A'>Visualizar Ativos</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");
		appendSTMI("false","<span class='menu'><a href='mecanico.php?modulo=buscar&Status=E'>Visualizar Excluidos</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		endSTMB();

	appendSTMI("false","<a href='#' onMouseOver=ShowHide('btadmin','btadminon'); onMouseOut=ShowHide('btadmin','btadminoff');><img border='0' name='btadmin' src='temas/imagens/btadminoff.gif'></a>","center","middle","","","110","53","5","normal","#ffffff","#cccccc","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","0","0","0","","","_self","Tahoma","9pt","#ffffff","normal","normal","none","Tahoma","9pt","#ffffff","normal","normal","none","0","solid","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","","temas/imagens/spacer.gif","temas/imagens/fade.gif","tiled","tiled");
    		beginSTMB("auto","0","0","vertically","","0","0","0","1","#4272B5","","tiled","#F58735","1","solid","0","Wipe down","25","8","0","0","0","0","0","0","#AEC906","false","#F58735","#F58735","#F58735","none");

		appendSTMI("false","<span class='menu'><a href='status.php?modulo=criar'>Adicionar Status</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","<span class='menu'><a href='status.php?modulo=buscar'>Visualizar Todas</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","","left","middle","","","11","11","0","normal","#F58735","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","9pt","#AEC906","normal","normal","none","Tahoma","9pt","#AEC906","normal","normal","none","0","none","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","<span class='menu'><a href='familia_master.php?modulo=criar'>Adicionar Família Master</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","<span class='menu'><a href='familia_master.php?modulo=buscar'>Visualizar Todas</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","","left","middle","","","11","11","0","normal","#F58735","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","9pt","#AEC906","normal","normal","none","Tahoma","9pt","#AEC906","normal","normal","none","0","none","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","<span class='menu'><a href='familia_acessorio_master.php?modulo=criar'>Adicionar Família Master de Acessório</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","<span class='menu'><a href='familia_acessorio_master.php?modulo=buscar'>Visualizar Todas</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","","left","middle","","","11","11","0","normal","#F58735","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","9pt","#AEC906","normal","normal","none","Tahoma","9pt","#AEC906","normal","normal","none","0","none","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","<span class='menu'><a href='familia.php?modulo=criar'>Adicionar Família</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","<span class='menu'><a href='familia.php?modulo=buscar'>Visualizar Todas</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","","left","middle","","","11","11","0","normal","#F58735","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","9pt","#AEC906","normal","normal","none","Tahoma","9pt","#AEC906","normal","normal","none","0","none","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","<span class='menu'><a href='familia_acessorio.php?modulo=criar'>Adicionar Família Acessório</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","<span class='menu'><a href='familia_acessorio.php?modulo=buscar'>Visualizar Todas</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");
		
appendSTMI("false","","left","middle","","","11","11","0","normal","#F58735","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","9pt","#AEC906","normal","normal","none","Tahoma","9pt","#AEC906","normal","normal","none","0","none","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","<span class='menu'><a href='grupo.php?modulo=criar'>Adicionar Grupo</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","<span class='menu'><a href='grupo.php?modulo=buscar'>Visualizar Todas</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

  		appendSTMI("false","","left","middle","","","11","11","0","normal","#F58735","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","9pt","#AEC906","normal","normal","none","Tahoma","9pt","#AEC906","normal","normal","none","0","none","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","","temas/imagens/spacer.gif","","tiled","tiled");  

		appendSTMI("false","<span class='menu'><a href='usuario.php?modulo=criar'>Adicionar Usuário</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","<span class='menu'><a href='usuario.php?modulo=buscar'>Visualizar Todos</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");
		appendSTMI("false","<span class='menu'><a href='perfil.php?modulo=buscar'>Gerenciar Perfil</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

  		appendSTMI("false","","left","middle","","","11","11","0","normal","#F58735","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","9pt","#AEC906","normal","normal","none","Tahoma","9pt","#AEC906","normal","normal","none","0","none","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","#AEC906","","temas/imagens/spacer.gif","","tiled","tiled");  

		appendSTMI("false","<span class='menu'><a href='patio.php?modulo=criar'>Adicionar Pátio</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","<span class='menu'><a href='patio.php?modulo=buscar'>Visualizar Todos</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");
		
		endSTMB();

	appendSTMI("false","<a href='#' onMouseOver=ShowHide('btrelatorios','btrelatorioson'); onMouseOut=ShowHide('btrelatorios','btrelatoriosoff');><img border='0' name='btrelatorios' src='temas/imagens/btrelatoriosoff.gif'></a>","center","middle","","","110","53","5","normal","#ffffff","#cccccc","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","0","0","0","","","_self","Tahoma","9pt","#ffffff","normal","normal","none","Tahoma","9pt","#ffffff","normal","normal","none","0","solid","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","","temas/imagens/spacer.gif","temas/imagens/fade.gif","tiled","tiled");	

		beginSTMB("auto","0","0","vertically","","0","0","0","1","#4272B5","","tiled","#F58735","1","solid","0","Wipe down","25","8","0","0","0","0","0","0","#AEC906","false","#F58735","#F58735","#F58735","none");

		appendSTMI("false","<span class='menu'><a href='relatorios.php?modulo=maquina'>Relatório de maquina</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","<span class='menu'><a href='relatorios.php?modulo=operador'>Relatório de operador</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");

		appendSTMI("false","<span class='menu'><a href='relatorios.php?modulo=maquinaporobra'>Relatório de MAQ/OBRA</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");	
		appendSTMI("false","<span class='menu'><a href='relatorios.php?modulo=notafiscal'>Notas Fiscais</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");	
		appendSTMI("false","<span class='menu'><a href='relatorios.php?modulo=resultadocomercial'>Resultados Comerciais</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");	
		appendSTMI("false","<span class='menu'><a href='relatorios.php?modulo=resultadocomercialfamilia'>Resultados Comerciais por Familia</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");	
		appendSTMI("false","<span class='menu'><a href='relatorios.php?modulo=resultadocomercialacessorio'>Resultados Comerciais de Acessório</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");	
		appendSTMI("false","<span class='menu'><a href='relatorios.php?modulo=resultadocomercialacessoriofamilia'>Resultados Comerciais de Acessório por Família</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");	
		appendSTMI("false","<span class='menu'><a href='relatorios.php?modulo=FrotaCapacidade'>Frota e Capacidade</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");	
		appendSTMI("false","<span class='menu'><a href='gerarelatorio9.php' target='_blank'>Relatório de obras sem Operador </a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");	
		appendSTMI("false","<span class='menu'><a href='gerarelatorio_comoperador.php' target='_blank'>Relatório de obras com Operador </a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");	
		appendSTMI("false","<span class='menu'><a href='relatorios.php?modulo=eqptoobra'>Última Obra</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");	
		appendSTMI("false","<span class='menu'><a href='form_entra_saida.php'>Programação de Entrada/Saída</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");	
		appendSTMI("false","<span class='menu'><a href='relatorios.php?modulo=frete'>Frete</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");	
		appendSTMI("false","<span class='menu'><a href='relatorios.php?modulo=resultadocomercialgrupo'>Resultados Comerciais por Grupo</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");	
		appendSTMI("false","<span class='menu'><a href='relatorios.php?modulo=MaquinaStatus'>Relatório de Disponibilidade Comercial</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");	
		appendSTMI("false","<span class='menu'><a href='relatorios.php?modulo=proprietario'>Relatório de maquina/proprietario</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");
		appendSTMI("false","<span class='menu'><a href='relatorios.php?modulo=mecanico'>Relatório de maquina/mecânico</a></span>","left","middle","","","11","11","0","normal","#F7F7F7","transparent","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","8","0","0","","","_self","Tahoma","-2pt","#ffffff","normal","normal","none","Tahoma","-2pt","#ffffff","normal","normal","none","0","none","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","#cccc00","","temas/imagens/spacer.gif","","tiled","tiled");
		endSTMB();

	appendSTMI("false","<a href='logout.php' onMouseOver=ShowHide('btdesconectar','btdesconectaron'); onMouseOut=ShowHide('btdesconectar','btdesconectaroff');><img border='0' name='btdesconectar' src='temas/imagens/btdesconectaroff.gif'></a>","center","middle","","","111","53","5","normal","#ffffff","#cccccc","","0","-1","-1","temas/imagens/spacer.gif","temas/imagens/spacer.gif","0","0","0","","","_self","Tahoma","9pt","#ffffff","normal","normal","none","Tahoma","9pt","#ffffff","normal","normal","none","0","solid","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","","temas/imagens/spacer.gif","temas/imagens/fade.gif","tiled","tiled");

endSTM();